# Generated by Django 4.2.1 on 2023-06-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_movie', '0003_alter_movie_image_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='update_at',
        ),
    ]
