# Generated by Django 4.2.1 on 2023-06-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog'),
            preserve_default=False,
        ),
    ]
