# Generated by Django 4.2.1 on 2023-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img/attack.jpg', upload_to='img/'),
        ),
    ]
