# Generated by Django 4.2.1 on 2023-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img/Attack.jpg', upload_to='img/'),
        ),
    ]
