# Generated by Django 4.2.1 on 2023-05-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='movies/images/', upload_to='movies/images'),
        ),
    ]
