# Generated by Django 4.1.7 on 2023-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_game_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
