# Generated by Django 4.2.1 on 2023-06-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='contant',
        ),
    ]
