# Generated by Django 4.2 on 2023-05-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2084)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
