# Generated by Django 4.2 on 2023-06-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_blog_publish_date_reviwe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviwe',
            new_name='Review',
        ),
    ]
