# Generated by Django 4.2 on 2023-06-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_rename_reviwe_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Comments',
        ),
    ]
