# Generated by Django 4.2.1 on 2023-05-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_content_blog_content_rename_title_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/abha_3.jpg', upload_to='images/'),
        ),
    ]
