# Generated by Django 4.2.1 on 2023-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
