# Generated by Django 4.2.1 on 2023-06-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updatedAt',
        ),
    ]
