# Generated by Django 4.2.1 on 2023-06-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publish_date',
            new_name='created_at',
        ),
    ]
