# Generated by Django 4.2.1 on 2023-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('context', models.TextField()),
                ('is_published', models.BooleanField()),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
